export const CATEGORY_COLOR_PRESETS = [
  "#1495FF",
  "#10B981",
  "#F97316",
  "#8B5CF6",
  "#EC4899",
  "#EAB308",
  "#EF4444",
  "#14B8A6",
  "#2563EB",
  "#A855F7",
  "#F59E0B",
  "#64748B",
] as const;

export const CATEGORY_ICON_PRESETS = [
  "shape-outline",
  "silverware-fork-knife",
  "shopping",
  "cash-plus",
  "wallet-outline",
  "car-outline",
  "filmstrip-box-multiple",
  "heart-pulse",
  "school",
  "airplane",
  "shopping-outline",
  "coffee-outline",
  "bookmark-outline",
  "shield-check-outline",
  "gift-outline",
  "laptop",
  "home-outline",
  "chart-line",
  "bank-outline",
  "receipt-text-outline",
  "parking",
  "gas-station-outline",
  "briefcase-outline",
  "piggy-bank-outline",
  "cellphone",
  "cart-outline",
] as const;

export const CATEGORY_EMOJI_PRESETS = [
  "🍔",
  "🛒",
  "🚗",
  "💼",
  "💸",
  "💰",
  "🎓",
  "🎁",
  "🏠",
  "☕",
  "✈️",
  "🎬",
  "📱",
  "🏥",
  "🐾",
  "📈",
] as const;
