// Centralized merchant logo registry and matching helpers
// Add your local bundled merchant logo images to the ASSETS map below.
// Example:
// import starbucks from "../assets/merchant-logos/starbucks.png";
// const ASSETS: Record<string, any> = { starbucks };

export function normalizeMerchantName(value?: string | null) {
  if (!value) return "";

  return value
    .trim()
    .toLowerCase()
    .replace(/\+/g, "plus")
    .replace(/&/g, " and ")
    .replace(/[\u2018\u2019\u201c\u201d]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Canonical alias map: map many possible merchant labels to a canonical key
const CANONICAL_ALIASES: Record<string, string> = {
  // coffee
  starbucks: "starbucks",
  "starbucks-coffee": "starbucks",

  // malls / stores
  sm: "sm",
  "sm-store": "sm",
  smstore: "sm",

  // airlines
  airasia: "airasia",
  "air-asia": "airasia",

  // banks
  bpi: "bpi",
  landbank: "landbank",

  // fuels
  shell: "shell",
  petron: "petron",

  // pharmacies
  "mercury-drug": "mercury-drug",
  mercurydrug: "mercury-drug",
  watsons: "watsons",

  // telco / utilities
  pldt: "pldt",

  // digital
  steam: "steam",
  "disney-plus": "disney-plus",
  "disney+": "disney-plus",
  canva: "canva",

  // ride services
  grab: "grab",
  moveit: "move-it",
  "move-it": "move-it",
  joyride: "joyride",
  angkas: "angkas",
};

// Static asset map. Populate this map with static imports of your bundled images.
// Keys should match the canonical keys above (eg. 'starbucks', 'sm', 'airasia').
export const ASSETS: Record<string, any> = {
  // Example:
  // starbucks: require("../assets/merchant-logos/starbucks.png"),
};

// Try to find a canonical key for a merchant name.
export function findMerchantLogoKey(
  merchantName?: string | null,
): string | null {
  if (!merchantName) return null;

  const n = normalizeMerchantName(merchantName);

  // Direct alias match
  if (CANONICAL_ALIASES[n]) return CANONICAL_ALIASES[n];

  // Exact match to alias key
  if (Object.prototype.hasOwnProperty.call(CANONICAL_ALIASES, n))
    return CANONICAL_ALIASES[n];

  // Substring match (safe partial matching): only match if token is at start or full token
  const tokens = n.split("-").filter(Boolean);
  for (const token of tokens) {
    if (CANONICAL_ALIASES[token]) return CANONICAL_ALIASES[token];
    if (ASSETS[token]) return token;
  }

  // Try fuzzy-ish match: if any canonical key is contained in the normalized string
  for (const key of Object.keys(CANONICAL_ALIASES)) {
    if (n.includes(key)) return CANONICAL_ALIASES[key];
  }

  // Finally, if we have an asset whose key matches a substring
  for (const key of Object.keys(ASSETS)) {
    if (n.includes(key)) return key;
  }

  return null;
}

export function getMerchantLogoAsset(merchantName?: string | null) {
  const key = findMerchantLogoKey(merchantName);
  if (!key) return null;
  return ASSETS[key] ?? null;
}

export default {
  normalizeMerchantName,
  findMerchantLogoKey,
  getMerchantLogoAsset,
  ASSETS,
};

/* AUTO-GENERATED-MERCHANT-LOGOS:START */
// This block is auto-generated by scripts/generate-merchant-logos.js
// Do not edit the lines between the START/END markers manually — they will be overwritten.

import airAsia from "../assets/merchant-logos/air-asia.webp";
import angkas from "../assets/merchant-logos/Angkas.jpg";
import ateneo from "../assets/merchant-logos/Ateneo.png";
import bench from "../assets/merchant-logos/Bench.jpg";
import bonchon from "../assets/merchant-logos/Bonchon.webp";
import caltex from "../assets/merchant-logos/Caltex.webp";
import canva from "../assets/merchant-logos/Canva.png";
import cebuPacific from "../assets/merchant-logos/cebu-pacific.webp";
import chatgpt from "../assets/merchant-logos/ChatGPT.jpg";
import chowking from "../assets/merchant-logos/Chowking.webp";
import converge from "../assets/merchant-logos/Converge.webp";
import deLaSalle from "../assets/merchant-logos/De-La-Salle.webp";
import disneyplus from "../assets/merchant-logos/Disneyplus.jpg";
import gcash from "../assets/merchant-logos/GCash.png";
import globe from "../assets/merchant-logos/Globe.webp";
import greenwich from "../assets/merchant-logos/Greenwich.png";
import jolibee from "../assets/merchant-logos/Jolibee.png";
import joyride from "../assets/merchant-logos/Joyride.png";
import kfc from "../assets/merchant-logos/KFC.png";
import landers from "../assets/merchant-logos/Landers.png";
import lazada from "../assets/merchant-logos/Lazada.png";
import mangInasal from "../assets/merchant-logos/Mang-Inasal.jpg";
import maya from "../assets/merchant-logos/Maya.jpg";
import maynilad from "../assets/merchant-logos/Maynilad.jpg";
import mcdonalds from "../assets/merchant-logos/Mcdonalds.jpg";
import meralco from "../assets/merchant-logos/Meralco.jpg";
import merucryDrug from "../assets/merchant-logos/Merucry-Drug.webp";
import miniso from "../assets/merchant-logos/Miniso.png";
import moveIt from "../assets/merchant-logos/Move-It.webp";
import nationalBookStore from "../assets/merchant-logos/National-Book-Store.webp";
import netflix from "../assets/merchant-logos/Netflix.jpg";
import petron from "../assets/merchant-logos/Petron.webp";
import pldt from "../assets/merchant-logos/PLDT.webp";
import puregold from "../assets/merchant-logos/Puregold.jpg";
import robinsonsSupermarket from "../assets/merchant-logos/Robinson-Supermarket.webp";
import sR from "../assets/merchant-logos/S&R.webp";
import savemore from "../assets/merchant-logos/Savemore.png";
import shell from "../assets/merchant-logos/Shell.webp";
import shopee from "../assets/merchant-logos/Shopee.webp";
import smHypermarket from "../assets/merchant-logos/SM-Hypermarket.webp";
import smParking from "../assets/merchant-logos/SM-Parking.webp";
import smStore from "../assets/merchant-logos/Sm-Store.jpg";
import sm from "../assets/merchant-logos/SM.webp";
import smart from "../assets/merchant-logos/Smart.webp";
import spotify from "../assets/merchant-logos/Spotify.png";
import starbucks from "../assets/merchant-logos/Starbucks.png";
import steam from "../assets/merchant-logos/Steam.jpg";
import timHortons from "../assets/merchant-logos/Tim-Hortons.png";
import tnt from "../assets/merchant-logos/TNT.webp";
import uniqlo from "../assets/merchant-logos/UNIQLO.webp";
import universityOfThePhilippines from "../assets/merchant-logos/University-of-the-Philippines.webp";
import watsons from "../assets/merchant-logos/Watsons.jpeg";

export const MERCHANT_LOGOS: Record<string, any> = {
  "air asia": airAsia,
  angkas: angkas,
  ateneo: ateneo,
  bench: bench,
  bonchon: bonchon,
  caltex: caltex,
  canva: canva,
  "cebu pacific": cebuPacific,
  chatgpt: chatgpt,
  chowking: chowking,
  converge: converge,
  "de la salle": deLaSalle,
  disney: disneyplus,
  "disney plus": disneyplus,
  disneyplus: disneyplus,
  globe: globe,
  greenwich: greenwich,
  gcash: gcash,
  jolibee: jolibee,
  joyride: joyride,
  kfc: kfc,
  landers: landers,
  lazada: lazada,
  "mang inasal": mangInasal,
  maya: maya,
  maynilad: maynilad,
  mcdonalds: mcdonalds,
  meralco: meralco,
  "merucry drug": merucryDrug,
  miniso: miniso,
  "move it": moveIt,
  "national book store": nationalBookStore,
  netflix: netflix,
  petron: petron,
  pldt: pldt,
  puregold: puregold,
  "robinsons supermarket": robinsonsSupermarket,
  "s and r": sR,
  "s r": sR,
  savemore: savemore,
  shell: shell,
  shopee: shopee,
  "sm hypermarket": smHypermarket,
  "sm parking": smParking,
  "sm store": smStore,
  sm: sm,
  smart: smart,
  spotify: spotify,
  starbucks: starbucks,
  steam: steam,
  "tim hortons": timHortons,
  tnt: tnt,
  uniqlo: uniqlo,
  "university of the philippines": universityOfThePhilippines,
  watsons: watsons,
};

/* AUTO-GENERATED-MERCHANT-LOGOS:END */
