const tokens = {
  light: {
    background: '#F5F7FA',
    foreground: '#1E2433',
    card: '#FFFFFF',
    cardForeground: '#151B28',
    primary: '#4F8CFF',
    primaryForeground: '#FFFFFF',
    secondary: '#EBEEF3',
    secondaryForeground: '#232B3A',
    muted: '#E3E7EC',
    mutedForeground: '#6B7485',
    destructive: '#F56565',
    success: '#48BB78',
    border: '#DFE3E8',
    ring: '#4F8CFF',
    chart: {
      1: '#4F8CFF',
      2: '#48BB78',
      3: '#F56565',
      4: '#8B7CF8',
      5: '#E8B24C',
    },
    gradients: {
      cardBlue: ['#4F8CFF', '#6E72FC'],
      cardTeal: ['#2EC8B8', '#4F8CFF'],
      cardDark: ['#1E2433', '#151B28'],
      cardGold: ['#F2C35B', '#E8B24C'],
    },
    glass: {
      background: 'rgba(255, 255, 255, 0.8)',
      backgroundStrong: 'rgba(255, 255, 255, 0.9)',
      border: 'rgba(223, 227, 232, 0.72)',
      borderStrong: 'rgba(223, 227, 232, 0.9)',
      shadow: 'rgba(15, 23, 42, 0.08)',
    },
  },
  dark: {
    background: '#0F172A',
    foreground: '#F8FAFC',
    card: '#1E293B',
    cardForeground: '#F8FAFC',
    primary: '#60A5FA',
    primaryForeground: '#0F172A',
    secondary: '#2D3748',
    secondaryForeground: '#F8FAFC',
    muted: '#374151',
    mutedForeground: '#9CA3AF',
    destructive: '#E53E3E',
    success: '#38A169',
    border: '#3F4A5A',
    ring: '#60A5FA',
    chart: {
      1: '#60A5FA',
      2: '#38A169',
      3: '#E53E3E',
      4: '#7C7BFA',
      5: '#D9A441',
    },
    gradients: {
      cardBlue: ['#60A5FA', '#7C7BFA'],
      cardTeal: ['#22C1B5', '#4F8CFF'],
      cardDark: ['#0F172A', '#1E293B'],
      cardGold: ['#E8B24C', '#D99829'],
    },
    glass: {
      background: 'rgba(30, 41, 59, 0.8)',
      backgroundStrong: 'rgba(30, 41, 59, 0.9)',
      border: 'rgba(63, 74, 90, 0.7)',
      borderStrong: 'rgba(96, 165, 250, 0.24)',
      shadow: 'rgba(2, 6, 23, 0.32)',
    },
  },
};

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './hooks/**/*.{js,jsx,ts,tsx}',
    './lib/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: tokens.light.background,
        foreground: tokens.light.foreground,
        card: tokens.light.card,
        'card-foreground': tokens.light.cardForeground,
        primary: tokens.light.primary,
        'primary-foreground': tokens.light.primaryForeground,
        secondary: tokens.light.secondary,
        'secondary-foreground': tokens.light.secondaryForeground,
        muted: tokens.light.muted,
        'muted-foreground': tokens.light.mutedForeground,
        destructive: tokens.light.destructive,
        success: tokens.light.success,
        border: tokens.light.border,
        ring: tokens.light.ring,
        chart: tokens.light.chart,
        'dark-background': tokens.dark.background,
        'dark-foreground': tokens.dark.foreground,
        'dark-card': tokens.dark.card,
        'dark-card-foreground': tokens.dark.cardForeground,
        'dark-primary': tokens.dark.primary,
        'dark-primary-foreground': tokens.dark.primaryForeground,
        'dark-secondary': tokens.dark.secondary,
        'dark-secondary-foreground': tokens.dark.secondaryForeground,
        'dark-muted': tokens.dark.muted,
        'dark-muted-foreground': tokens.dark.mutedForeground,
        'dark-destructive': tokens.dark.destructive,
        'dark-success': tokens.dark.success,
        'dark-border': tokens.dark.border,
        'dark-ring': tokens.dark.ring,
        'dark-chart': tokens.dark.chart,
        glass: tokens.light.glass.background,
        'glass-strong': tokens.light.glass.backgroundStrong,
        'glass-border': tokens.light.glass.border,
      },
      fontFamily: {
        sans: ['Inter', 'Geist', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'Geist Mono Fallback', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['16px', { lineHeight: '24px' }],
        lg: ['18px', { lineHeight: '28px' }],
        xl: ['20px', { lineHeight: '30px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '38px' }],
        '4xl': ['36px', { lineHeight: '44px' }],
        '5xl': ['48px', { lineHeight: '56px' }],
      },
      borderRadius: {
        sm: '12px',
        md: '16px',
        lg: '20px',
        xl: '24px',
        '2xl': '28px',
        '3xl': '32px',
      },
    },
  },
  plugins: [],
};
